### ISSUE TITLE
Speed up downloads - avoid showing progress

### ISSUE THREAD

**Issue by bsousapt** [lamw/vmworld2019-session-urls#1]
Hi William,

Thanks for getting the download script available and noticed that with a quick change the download speeds can be improved.
In short all is needed is to disable the download progress meter with the $progressPreference variable.

I added the variable as seen in the snippet bellow : 
        Write-Host "Downloading $title ..."
		**$progressPreference = 'silentlyContinue'**
        Invoke-WebRequest -Uri $url -Headers $headers -Outfile $title
    }

In my case it meant that i went from sub 1.5 MB/s download to around 2.2MB/s with peaks > 4 MB/s .

![download-02](https://user-images.githubusercontent.com/10531381/64118131-e9054e80-cd8e-11e9-815f-d5687046b30b.jpg)

Maybe worth to consider adding this option. 

Cheers
Bruno

**Comment by lamw** [comment]
Thanks for the feedback! I'll make the change in the script
